
MAT216 LAB 3
---
NAME : ANIKA ISLAM 

ID : 21101298 

SECTION : 7 



Find the LU decomposition and solve the equation using sympy for part A and numpy for part B: 
$ \begin{bmatrix}
-6 & -5 & -8 \\
8 & -5 & 6 \\
-2 & -8 & -3 \\
\end{bmatrix} \begin{bmatrix}
\boldsymbol{x}_1 \\
\boldsymbol{x}_2 \\
\boldsymbol{x}_3 
\end{bmatrix} = \begin{bmatrix}
9\\
7\\
-6 \\
\end{bmatrix}
 $ 



In [ ]:
# PART A 
from sympy import Matrix
from sympy import init_printing 
A = Matrix([[-6,-5,-8],[8,-5,6],[-2,-8,-3]])
L,U,_ = A.LUdecomposition()
init_printing(use_latex = 'matplotlib')
L

⎡ 1    0   0⎤
⎢           ⎥
⎢-4/3  1   0⎥
⎢           ⎥
⎢      19   ⎥
⎢1/3   ──  1⎥
⎣      35   ⎦

In [ ]:
U

⎡-6   -5     -8  ⎤
⎢                ⎥
⎢0   -35/3  -14/3⎥
⎢                ⎥
⎣0     0    11/5 ⎦

In [ ]:
_

⎡-6   -5     -8  ⎤
⎢                ⎥
⎢0   -35/3  -14/3⎥
⎢                ⎥
⎣0     0    11/5 ⎦

In [ ]:
# PART B 
import numpy as np
L = np.array([[1,0,0],[-4/3,1,0],[1/3,19/35,1]])
U = np.array([[-6,-5,-8],[0,-35/3,-14/3],[0,0,11/5]])
B = np.array([9,7,-6]) 

B_L = np.zeros(B.shape[0]) # (3,1) - > np.zeros(3) -> [0. 0. 0. ]
print(B_L)
# Forward Substitution [Ly = b]
for i in range(L.shape[0]): #(3,3) -> (3) -> (0,3) -> 0,1,2
    summation=0 
    for j in range(L.shape[0]):  # i(row) = 2 , j(elem) = 2 -> [9. 19. 0.]
        if i == j:
            B_L[j] = B[j] - summation
            B_L[j] = B_L[j]/L[i,j] 
            break
        else:
            summation = summation + L[i,j]*B_L[j]

# Flip U and B_L [For B_l,y1,y2,y3 -> y3,y2,y1]
print(U)
print()
U = np.flip(U, 0)
print(U)
print()
U = np.flip(U, 1)
print(U)
print()
print(B_L)
B_L = np.flip(B_L,0)
print(B_L)
print()

# Backward Substitution [Ux = y]
B_LU = np.zeros(B_L.shape[0])
for i in range(U.shape[0]):
  summation=0
  for j in range(U.shape[0]):
    if i == j:
      B_LU[j] = B_L[j] - summation
      B_LU[j] = B_LU[j]/U[i,j]
      break
    else:
      summation = summation + U[i,j]*B_LU[j]

# Flip B_LU [For B_LU, x3,x2,x1 -> x1,x2,x3]
print(np.flip(B_LU, 0))
print()

#Print the answer 
count=1
for i in range(len(B_LU)-1, -1, -1):
  print("x"+str(count)+":",B_LU[i])
  count+=1

print()

[0. 0. 0.]
[[ -6.          -5.          -8.        ]
 [  0.         -11.66666667  -4.66666667]
 [  0.           0.           2.2       ]]

[[  0.           0.           2.2       ]
 [  0.         -11.66666667  -4.66666667]
 [ -6.          -5.          -8.        ]]

[[  2.2          0.           0.        ]
 [ -4.66666667 -11.66666667   0.        ]
 [ -8.          -5.          -6.        ]]

[  9.          19.         -19.31428571]
[-19.31428571  19.           9.        ]

[ 8.63636364  1.88311688 -8.77922078]
x1: -8.779220779220777

x1: 8.636363636363635
x2: 1.8831168831168825
x3: -8.779220779220777

